sudo: required
language: generic

matrix:
  include:
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: unstable
        TRAVIS_DEBIAN_AUTOPKGTEST: false
        DEB_BUILD_OPTIONS: parallel=4
      services:
        - docker
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: testing
        TRAVIS_DEBIAN_AUTOPKGTEST: false
        DEB_BUILD_OPTIONS: parallel=4
      services:
        - docker
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: stable
        TRAVIS_DEBIAN_BACKPORTS: true
        TRAVIS_DEBIAN_AUTOPKGTEST: false
      services:
        - docker
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: unstable
        TRAVIS_DEBIAN_AUTOPKGTEST: true
        DEB_BUILD_OPTIONS: nocheck
      services:
        - docker
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: testing
        TRAVIS_DEBIAN_AUTOPKGTEST: true
        DEB_BUILD_OPTIONS: nocheck
      services:
        - docker
    - env:
        TRAVIS_DEBIAN_DISTRIBUTION: stable
        TRAVIS_DEBIAN_BACKPORTS: true
        TRAVIS_DEBIAN_AUTOPKGTEST: true
        DEB_BUILD_OPTIONS: nocheck
      services:
        - docker

script:
  - wget -O- http://travis.debian.net/script.sh | sh -

branches:
  except:
    - /^debian\/\d/

if:
  tag IS blank
